# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sightrix(object):
    def setupUi(self, Sightrix):
        Sightrix.setObjectName("Sightrix")
        Sightrix.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(Sightrix)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(".\\Images/new-bg.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1640, 820, 181, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet(
            "background-color: blue;\n"
            " color: #fff;\n"
            " border: none;\n"
            " border-radius: 8px;\n"
            " padding: 10px 20px;\n"
            " font-size: 30px;\n"
            " font-weight: bold;\n"
            " cursor: pointer;\n"
            " transition: background-color 0.3s ease;"
        )
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1640, 900, 181, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet(
            "background-color: red;\n"
            " color: #fff;\n"
            " border: none;\n"
            " border-radius: 8px;\n"
            " padding: 10px 20px;\n"
            " font-size: 30px;\n"
            " font-weight: bold;\n"
            " cursor: pointer;\n"
            " transition: background-color 0.3s ease;"
        )
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(860, 80, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Imprint MT 63")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet(
            "background: transparent;\n"
            "border: none;\n"
            "color: green;\n"
            "font-size: 50px;\n"
            "font-family: Imprint MT Shadow;\n"
            "margin-top:0px;\n"
            "margin-bottom:0px;\n"
            "margin-left:0px;\n"
            "margin-right:0px;\n"
            "-qt-block-indent:0;\n"
            "text-indent:0px;"
        )
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setObjectName("textBrowser")
        Sightrix.setCentralWidget(self.centralwidget)

        self.retranslateUi(Sightrix)
        QtCore.QMetaObject.connectSlotsByName(Sightrix)

    def retranslateUi(self, Sightrix):
        _translate = QtCore.QCoreApplication.translate
        Sightrix.setWindowTitle(
            _translate("Sightrix", "Sightrix - Pioneering Accessibility")
        )
        self.pushButton.setText(_translate("Sightrix", "Start"))
        self.pushButton_2.setText(_translate("Sightrix", "Exit"))
        self.textBrowser.setHtml(
            _translate(
                "Sightrix",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'Imprint MT 63'; font-size:50px; font-weight:400; font-style:normal;\">\n"
                '<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p></body></html>',
            )
        )


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Sightrix = QtWidgets.QMainWindow()
    ui = Ui_Sightrix()
    ui.setupUi(Sightrix)
    Sightrix.show()
    sys.exit(app.exec_())
