# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvis.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JarvisVirtualAssistant(object):
    def setupUi(self, JarvisVirtualAssistant):
        JarvisVirtualAssistant.setObjectName("JarvisVirtualAssistant")
        JarvisVirtualAssistant.resize(1392, 694)
        self.label = QtWidgets.QLabel(JarvisVirtualAssistant)
        self.label.setGeometry(QtCore.QRect(0, 0, 1631, 761))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Images/background.gif"))
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(JarvisVirtualAssistant)
        self.pushButton.setGeometry(QtCore.QRect(1190, 660, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet(
            "background-color: rgb(0, 255, 0);\n" "border-radius: 8px;"
        )
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(JarvisVirtualAssistant)
        self.pushButton_2.setGeometry(QtCore.QRect(1280, 660, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet(
            "background-color: rgb(255, 0, 0);\n" "border-radius: 8px;"
        )
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(JarvisVirtualAssistant)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 431, 141))
        self.label_2.setStyleSheet("border: 2px solid white;\n" "border-radius: 8px;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Images/coding.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(JarvisVirtualAssistant)
        self.textBrowser.setGeometry(QtCore.QRect(790, 20, 256, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet(
            "background: transparent;\n"
            "border-radius: 6px;\n"
            "color: rgb(0, 255, 0);\n"
            "font-size: 22px;\n"
            "font-weight: 500;\n"
            ""
        )
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(JarvisVirtualAssistant)
        self.textBrowser_2.setGeometry(QtCore.QRect(1110, 20, 256, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet(
            "background: transparent;\n"
            "border-radius: 6px;\n"
            "color: rgb(0, 255, 0);\n"
            "font-size: 22px;\n"
            "font-weight: 500;\n"
            ""
        )
        self.textBrowser_2.setObjectName("textBrowser_2")

        self.retranslateUi(JarvisVirtualAssistant)
        QtCore.QMetaObject.connectSlotsByName(JarvisVirtualAssistant)

    def retranslateUi(self, JarvisVirtualAssistant):
        _translate = QtCore.QCoreApplication.translate
        JarvisVirtualAssistant.setWindowTitle(
            _translate("JarvisVirtualAssistant", "Jarvis Virtual Assistant")
        )
        self.pushButton.setText(_translate("JarvisVirtualAssistant", "Run"))
        self.pushButton_2.setText(_translate("JarvisVirtualAssistant", "Exit"))
        self.textBrowser.setHtml(
            _translate(
                "JarvisVirtualAssistant",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'Bahnschrift'; font-size:22px; font-weight:496; font-style:normal;\">\n"
                "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:'MS Shell Dlg 2';\"><br /></p></body></html>",
            )
        )
        self.textBrowser_2.setHtml(
            _translate(
                "JarvisVirtualAssistant",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'Bahnschrift'; font-size:22px; font-weight:496; font-style:normal;\">\n"
                "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:'MS Shell Dlg 2';\"><br /></p></body></html>",
            )
        )


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    JarvisVirtualAssistant = QtWidgets.QDialog()
    ui = Ui_JarvisVirtualAssistant()
    ui.setupUi(JarvisVirtualAssistant)
    JarvisVirtualAssistant.show()
    sys.exit(app.exec_())
